# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName' 
    #erviceConnection: 'Build Notification to cddirector.io'
    method: 'POST' 
    headers: '{Content-Type:application/json, PlanUrl: $(system.CollectionUri), ProjectId: $(system.TeamProjectId), HubName: $(system.HostType), PlanId: $(system.PlanId), JobId: $(system.JobId), TimelineId: $(system.TimelineId), TaskInstanceId: $(system.TaskInstanceId), AuthToken: $(system.AccessToken)}' 
    body: '{"applicationName": "ADO","applicationVersionBuildNumber": "Assaf-2","applicationVersionBuildUrl": "https://cddirector.io/","applicationVersionName": "master", "buildStartTime": "0"}'
    waitForCompletion: 'true' 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
