# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
jobs:
- job: sendNotificationToCdd
  pool: server
  steps:
    - 
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'CDD'
    method: 'POST'
    headers: |
      {
      "Content-Type":"application/json", 
      "PlanUrl": "$(system.CollectionUri)", 
      "ProjectId": "$(system.TeamProjectId)", 
      "HubName": "$(system.HostType)", 
      "PlanId": "$(system.PlanId)", 
      "JobId": "$(system.JobId)", 
      "TimelineId": "$(system.TimelineId)", 
      "TaskInstanceId": "$(system.TaskInstanceId)", 
      "AuthToken": "bearer $(system.AccessToken)"
      }
    waitForCompletion: 'false'